---
# ══════════════════════════════════════════════
# Rôle : grafana — orchestrateur des tâches
# ══════════════════════════════════════════════

- ansible.builtin.import_tasks: repo.yaml
- ansible.builtin.import_tasks: install.yaml
- ansible.builtin.import_tasks: configure.yaml
- ansible.builtin.import_tasks: service.yaml
