---
# ══════════════════════════════════════════════
# Variables groupe dmz — VLAN 20 (10.20.0.0/24)
# ══════════════════════════════════════════════

# ─── Réseau ───
atlas_group_vlan_id: 20
atlas_group_subnet: "10.20.0.0/24"
atlas_group_gateway: "10.20.0.1"
