---
# ══════════════════════════════════════════════
# Rôle : glpi_seed — orchestrateur des tâches
# ══════════════════════════════════════════════

- ansible.builtin.import_tasks: api_enable.yaml
- ansible.builtin.import_tasks: seed.yaml
