---
# ══════════════════════════════════════════════
# Variables groupe mgmt — VLAN 90 (10.90.0.0/24)
# ══════════════════════════════════════════════

# ─── Réseau ───
atlas_group_vlan_id: 90
atlas_group_subnet: "10.90.0.0/24"
atlas_group_gateway: "10.90.0.1"
