---
# ══════════════════════════════════════════════
# Rôle : zabbix — orchestrateur des tâches
# ══════════════════════════════════════════════

- ansible.builtin.import_tasks: repo.yaml
- ansible.builtin.import_tasks: install_server.yaml
- ansible.builtin.import_tasks: database.yaml
- ansible.builtin.import_tasks: configure_server.yaml
- ansible.builtin.import_tasks: tls.yaml
- ansible.builtin.import_tasks: install_frontend.yaml
- ansible.builtin.import_tasks: service.yaml
- ansible.builtin.import_tasks: register_hosts.yaml
